on:
  push:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to login to AWS

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        repository: DevopsGuyXD/Github_actions_custom
        ref: refs/heads/aws_login
    
    - name: ls
      run: |
          ls

    - name: AWS login
      id: aws_login
      uses: ./
      with:
        access_key_id: 'AKIAYUOXBHDKRROR2TRK'
        access_key_secret: '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'
        region: 'ap-south-1'
        
    - name: aws check   
      run: |
         aws configure list
