on:
  push:
    branches: [ main ]

jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest
    name: A job to login to AWS

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        repository: DevopsGuyXD/Github_actions_custom
        ref: refs/heads/aws_login

    - name: AWS login
      id: aws_login
      uses: ./
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
        REGION: ${{ secrets.REGION }}
      with:
<<<<<<< HEAD
        access_key_id: $ACCESS_KEY_ID
        access_key_secret: $ACCESS_KEY_SECRET
        region: $REGION
=======
        access_key_id: 'AKIAYUOXBHDKRROR2TRK'
        access_key_secret: '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'
        region: 'ap-south-1'
>>>>>>> 22f7b3b8443b1e68939bdc8945f14ef2de638db0
