on:
  push:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to login to AWS

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        repository: DevopsGuyXD/Github_actions_custom
        ref: refs/heads/aws_login